apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-fulfillment-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: order-fulfillment

  source:
    repoURL: https://github.com/haz365/order-fulfillment
    targetRevision: main
    path: k8s/charts/order-fulfillment
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
        - name: global.imageTag
          value: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: order-fulfillment

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas