apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: order-fulfillment
data:
  DB_HOST:       postgres
  DB_PORT:       "5432"
  DB_NAME:       fulfillment
  DB_USER:       appuser
  DB_SSL_MODE:   require
  AWS_REGION:    eu-west-2
  SQS_QUEUE_URL: REPLACE_WITH_SQS_URL